project_name: rsg
release:
  github:
    owner: mhausenblas
    name: right-size-guide
builds:
  - id: right-size-guide
    goos:
    - linux
    - darwin
    goarch:
    - amd64
    - arm
    - arm64
    env:
      - CGO_ENABLED=0
      - GO111MODULE=on
    main: .
archives:
  - id: right-size-guide
    builds:
    - right-size-guide
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"
